language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
before_script:
  - php -S 127.0.0.1:8000 -t tests/PHPCurlClass/ &
script:
  - cd tests && phpunit --configuration phpunit.xml
