language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "5.3" ]]; then sh -c "php -S 127.0.0.1:8000 -t tests/PHPCurlClass/ &"; fi
script:
  - php -l src/*
  - if [[ "$TRAVIS_PHP_VERSION" != "5.3" ]]; then cd tests && phpunit --configuration phpunit.xml; fi
