language: php

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
    - php: nightly
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
      dist: trusty
    - php: hhvm-nightly
      dist: trusty
    - nightly

before_script:
  - bash tests/before_script.sh

script:
  - bash tests/script.sh
