name: ci

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']
    name: PHP ${{ matrix.php }}

    steps:
      - name: set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: checkout
        uses: actions/checkout@v2

      - run: |
          bash tests/before_script.sh
          bash tests/script.sh
        env:
          TRAVIS_PHP_VERSION: ${{ matrix.php }}
