name: ci

on:
  push:
    branches:
      - master
      - php5.x-master
  pull_request:
  schedule:
    - cron: '0 17 * * *'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
        future-release: [false]
        include:
          - php: '8.1'
            future-release: true
          - php: '8.2'
            future-release: true
      fail-fast: false
    name: PHP ${{ matrix.php }}
    continue-on-error: ${{ matrix.future-release }}

    steps:
      - name: Set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: bash tests/ci.sh
        env:
          CI_PHP_VERSION: ${{ matrix.php }}
